pcd = read.csv("household_power_consumption.txt", sep=";", dec=".", colClasses = c("character", "character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"), na.strings=c("NA","?"))
pcd$Date = as.Date(pcd$Date, format="%d/%m/%Y")
pcd = subset(pcd, pcd$Date >= "2007-02-01" & pcd$Date <= "2007-02-02")
pcd$Date1 = paste(pcd$Date, pcd$Time, sep=" ")
pcd$Date2 = strptime(pcd$Date1, "%Y-%m-%d %H:%M:%S")
png(filename = "plot4.png")
par(mfrow=c(2,2))
plot(pcd$Date2, pcd$Global_active_power, type = "l", xlab = "", ylab = "Global Acive Power (kilowatts)")
plot(pcd$Date2, pcd$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(pcd$Date2, pcd$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
lines(pcd$Date2, pcd$Sub_metering_1, col="black")
lines(pcd$Date2, pcd$Sub_metering_2, col="red")
lines(pcd$Date2, pcd$Sub_metering_3, col="blue")
legend("topright", lty=7, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), cex=0.75)
plot(pcd$Date2, pcd$Global_reactive_power, type = "l", xlab = "datetime", ylab="Global_reactive_power")
dev.off()
